INSERT OVERWRITE TABLE returns_ship_cons_l1_hive_fact

SELECT A.vendor_tracking_id,
A.first_received_dh_id,
CAST(A.first_received_dh_time as TIMESTAMP) as first_received_dh_time,
A.first_received_pc_id,
CAST(A.first_received_pc_time as TIMESTAMP) as first_received_pc_time,
A.first_received_mh_id,
CAST(A.first_received_mh_time as TIMESTAMP) as first_received_mh_time,
A.second_received_mh_id,
CAST(A.second_received_mh_time as TIMESTAMP) as second_received_mh_time,
A.third_received_mh_id,
CAST(A.third_received_mh_time as TIMESTAMP) as third_received_mh_time,
A.fourth_received_mh_id,
CAST(A.fourth_received_mh_time as TIMESTAMP) as fourth_received_mh_time,
A.last_received_dh_id,
CAST(A.last_received_dh_time as TIMESTAMP) as last_received_dh_time,
A.last_received_mh_id,
CAST(A.last_received_mh_time as TIMESTAMP) as last_received_mh_time,
A.second_last_received_mh_id,
CAST(A.second_last_received_mh_time as TIMESTAMP) as second_last_received_mh_time, 
B.first_cons_create_dh_id,
B.first_cons_create_dh_dest_id,
CAST(B.first_cons_create_dh_time as TIMESTAMP) as first_cons_create_dh_time, 
CAST(B.first_cons_create_dh_receive_time as TIMESTAMP) as first_cons_create_dh_receive_time,
B.first_cons_create_mh_id,
B.first_cons_create_mh_dest_id,
CAST(B.first_cons_create_mh_time as TIMESTAMP) as first_cons_create_mh_time,
CAST(B.first_cons_create_mh_receive_time as TIMESTAMP) as first_cons_create_mh_receive_time,
B.second_cons_create_mh_id,
B.second_cons_create_mh_dest_id,
CAST(B.second_cons_create_mh_time as TIMESTAMP) as second_cons_create_mh_time,
CAST(B.second_cons_create_mh_receive_time as TIMESTAMP) as second_cons_create_mh_receive_time,
B.third_cons_create_mh_id,
B.third_cons_create_mh_dest_id,
CAST(B.third_cons_create_mh_time as TIMESTAMP) as third_cons_create_mh_time,
CAST(B.third_cons_create_mh_receive_time as TIMESTAMP) as third_cons_create_mh_receive_time,
B.last_cons_create_mh_id,
B.last_cons_create_mh_dest_id,
CAST(B.last_cons_create_mh_time as TIMESTAMP) as last_cons_create_mh_time,
CAST(B.last_cons_create_mh_receive_time as TIMESTAMP) as last_cons_create_mh_receive_time,
B.sec_last_cons_create_mh_id,
B.sec_last_cons_create_mh_dest_id,
CAST(B.sec_last_cons_create_mh_time as TIMESTAMP) as sec_last_cons_create_mh_time,
CAST(B.sec_last_cons_create_mh_receive_time as TIMESTAMP) as sec_last_cons_create_mh_receive_time,
B.last_cons_dest_dh_id,
B.last_cons_dh_source_hub_id,
CAST(B.last_cons_dh_source_create_time as TIMESTAMP) as last_cons_dh_source_create_time,
CAST(B.last_cons_dh_receive_time as TIMESTAMP) as last_cons_dh_receive_time

from bigfoot_external_neo.scp_ekl__returns_shipment_l0_hive_fact A
left join bigfoot_external_neo.scp_ekl__returns_cons_l0_hive_fact B
ON A.vendor_tracking_id=B.vendor_tracking_id;
