
INSERT OVERWRITE TABLE returns_breach_funnel_l3_fact

select Distinct
T1.vendor_tracking_id as vendor_tracking_id,
T1.rvp_schedule_date_key as rvp_schedule_date_key,
T1.promised_completion_date_key as promised_completion_date_key,
T1.actual_completion_date_key as actual_completion_date_key,
T1.seller_type as seller_type,
T1.reverse_shipment_type as reverse_shipment_type,
T1.shipment_current_status as shipment_current_status,
T1.ekl_fin_zone as ekl_fin_zone,
T1.ekl_shipment_type as ekl_shipment_type,
T1.customer_dependency_flag as customer_dependency_flag, 
T1.ekl_dependency_flag as ekl_dependency_flag,
T1.pickup_added_sunday_flag as pickup_added_sunday_flag, 
T1.dh_breach_flag as dh_breach_flag,
T1.transport_breach_flag as transport_breach_flag,
T1.mh_breach_flag as mh_breach_flag,
T1.rc_or_ph_breach_flag as rc_or_ph_breach_flag,
T1.e2e_breach_flag as e2e_breach_flag,
T1.pickup_time_in_hours as pickup_time_in_hours,
T1.dh_processing_time_in_hours as dh_processing_time_in_hours,
T1.tc_dh_to_1st_mh_time_in_hours as tc_dh_to_1st_mh_time_in_hours,
T1.first_mh_to_cons_time_in_hours as first_mh_to_cons_time_in_hours,
T1.tc_1stmh_to_last_mh_time_in_hours as tc_1stmh_to_last_mh_time_in_hours,
T1.last_mh_to_cons_time_in_hours as last_mh_to_cons_time_in_hours,
T1.tc_last_mh_to_ph_time_in_hours as tc_last_mh_to_ph_time_in_hours,
T1.rcin_or_ph_to_complete_time_in_hours as rcin_or_ph_to_complete_time_in_hours,
T1.first_dh_hub_id_key as first_dh_hub_id_key,
T1.first_dh_hub_name as first_dh_hub_name,
T1.first_dh_hub_city as first_dh_hub_city,
T1.first_mh_hub_id_key as first_mh_hub_id_key,
T1.first_mh_hub_name as first_mh_hub_name,
T1.first_mh_hub_city as first_mh_hub_city,
T1.last_mh_hub_id_key as last_mh_hub_id_key,
T1.last_mh_hub_name as last_mh_hub_name,
T1.last_mh_hub_city as last_mh_hub_city,
T1.last_dh_hub_id_key as last_dh_hub_id_key,
T1.last_dh_hub_name as last_dh_hub_name,
T1.last_dh_hub_city as last_dh_hub_city,
T1.rvp_start_date1 as rvp_start_date1,
T1.first_received_dh_date1 as first_received_dh_date1,
T1.first_cons_create_dh_date1 as first_cons_create_dh_date1,
T1.first_cons_create_dh_receive_date1 as first_cons_create_dh_receive_date1,
T1.first_received_mh_date1 as first_received_mh_date1,
T1.first_cons_create_mh_date1 first_cons_create_mh_date1,
T1.sec_last_cons_create_mh_receive_date1 as sec_last_cons_create_mh_receive_date1,
T1.last_received_mh_date1 as last_received_mh_date1,
T1.last_cons_create_mh_date1 as last_cons_create_mh_date1,
T1.last_cons_create_mh_receive_date1 as last_cons_create_mh_receive_date1,
T1.last_received_dh_date1 as last_received_dh_date1,
T1.rvp_complete_date1 as rvp_complete_date1,
T1.rvp_schedule_date_key as rvp_schedule_date_key,
T1.rvp_schedule_time_key as rvp_schedule_time_key,
T1.dh_in_date_key as dh_in_date_key,
T1.dh_in_time_key as dh_in_time_key,
T1.dh_out_date_key as dh_out_date_key,
T1.dh_out_time_key as dh_out_time_key,
T1.first_mh_in_date_key as first_mh_in_date_key,
T1.first_mh_in_time_key as first_mh_in_time_key,
T1.first_mh_out_date_key as first_mh_out_date_key,
T1.first_mh_out_time_key as first_mh_out_time_key,
T1.last_mh_in_date_key as last_mh_in_date_key,
T1.last_mh_in_time_key as last_mh_in_time_key,
T1.last_mh_out_date_key as last_mh_out_date_key,
T1.last_mh_out_time_key as last_mh_out_time_key,
T1.phin_or_mh_shipment_out_date_key as phin_or_mh_shipment_out_date_key,
T1.phin_or_mh_shipment_out_time_key as phin_or_mh_shipment_out_time_key,
T1.rvp_complete_date_key as rvp_complete_date_key,
T1.rvp_complete_time_key as rvp_complete_time_key

FROM 
bigfoot_external_neo.scp_ekl__returns_breach_funnel_l3_hive_fact T1;

