INSERT OVERWRITE TABLE goods_recon_l2_fact
select 
return_item_id                           ,
return_id                                ,
order_item_id                            ,
return_item_quantity                     ,
return_item_shipment_id                  ,
return_item_tracking_id                  ,
courier_name                             ,
return_courier_bucket                    ,
return_quantity_recvd_in_wh              ,
return_quantity_rvp_done                 ,
return_item_notional_value               ,
return_reason                            ,
return_quantity_qc_passed                ,
return_quantity_qc_failed                ,
oms_qc_reason                            ,
oms_qc_comment                           ,
tenant_id                                ,
seller_id                                ,
seller_bucket                            ,
return_sub_reason                        ,
exchange_fsn_key                         ,
exchange_fsn                             ,
return_pickup_promise_date               ,
external_order_id                        ,
return_status                            ,
return_to_address_id                     ,
return_customer_will_send                ,
return_action                            ,
return_type                              ,
return_request_channel                   ,
return_amount                            ,
return_comments                          ,
returned_product_id_key                  ,
return_request_date                      ,
return_reason_bucket_key                 ,
return_courier_name_key                  ,
seller_id_key                            ,
return_pickup_promise_date_key           ,
return_product_listing_id_key            ,
return_request_date_key                  ,
order_id                                 ,
order_external_id                        ,
order_item_selling_price                 ,
order_item_seller_id                     ,
order_item_seller_id_key                 ,
order_item_quantity                      ,
order_shipping_address_id_key            ,
return_item_product_title                ,
return_item_product_id                   ,
return_item_product_id_key               ,
return_item_category_id                  ,
order_item_type                          ,
order_item_date                          ,
--account_id                               ,
shipment_item_id                         ,
shipment_display_id                      ,
shipment_id                              ,
shipment_return_warehouse_id             ,
shipment_type                            ,
shipment_destination_type                ,
wh_rvp_rto_flag                          ,
shipment_item_status                     ,
shipment_item_quantity                   ,
shipment_courier_name                    ,
shipment_item_is_excess                  ,
shipment_is_tampered                     ,
warehouse_id                             ,
shipment_item_order_item_id              ,
return_numdate,
return_numdate_key,
return_customer_will_return,
action_override_count,
return_item_value
from bigfoot_external_neo.scp_ekl__goods_recon_l2_hive_fact
