INSERT OVERWRITE TABLE fc_qc_tickets_l0_hive_fact
select warehouse_company,
qc_ticket_entity_id,
qc_ticket_created_at,
qc_ticket_created_date_key,
qc_ticket_created_time_key,
qc_ticket_created_by,
goods_receipt_note_id,
qc_ticket_id,
qc_ticket_lost_quantity,
qc_ticket_product_id,
qc_reason_id,
qc_ticket_quantity,
qc_ticket_status,
qc_ticket_updated_at,
qc_ticket_updated_date_key,
qc_ticket_updated_time_key,
qc_ticket_updated_by,
qc_ticket_warehouse_id,
qc_ticket_wid,
qc_ticket_product_key,
qc_ticket_warehouse_id_key,
ticket_status_created,
ticket_created_time,
ticket_created_date_key,
ticket_created_time_key,
ticket_status_pending_reco,
ticket_pending_reco_time,
ticket_pending_reco_date_key,
ticket_pending_reco_time_key,
ticket_status_bd_escalated,
ticket_bd_escalated_time,
ticket_bd_escalated_date_key,
ticket_bd_escalated_time_key,
ticket_status_marked_4_liquidn,
ticket_marked_4_liquidn_time,
ticket_marked_4_liquidn_date_key,
ticket_marked_4_liquidn_time_key,
ticket_status_marked_4_supplier_return,
ticket_marked_4_supplier_ret_time,
ticket_marked_4_sup_ret_date_key,
ticket_marked_4_sup_ret_time_key,
ticket_status_invalid,
ticket_invalid_time,
ticket_invalid_date_key,
ticket_invalid_time_key,
ticket_final_status_lost,
ticket_lost_time,
ticket_lost_date_key,
ticket_lost_time_key,
ticket_final_status_rejected,
ticket_reject_time,
ticket_reject_date_key,
ticket_reject_time_key,
ticket_status_sent_2_liquidn,
ticket_sent_2_liquidn_time,
ticket_sent_2_liquidn_date_key,
ticket_sent_2_liquidn_time_key,
ticket_status_sent_2_supp_ret,
ticket_sent_2_supp_ret_time,
ticket_sent_2_supp_ret_date_key,
ticket_sent_2_supp_ret_time_key,
ticket_status_wh_accepted,
ticket_wh_accepted_time,
ticket_wh_accepted_date_key,
ticket_wh_accepted_time_key,
ticket_bd_accepted_time,
ticket_bd_accepted_date_key,
ticket_bd_accepted_time_key,
bd_accepted_by,
warehouse_accepted_by,
sent_to_supplier_return_by,
lost_by,
rejected_by,
invalid_by,
sent_to_liquidation_by,
marked_for_supplier_return_by,
marked_for_liquidation_by,
bd_escalated_by,
pending_reco_by
from (
select 'wsr' as warehouse_company,
-- qc_ticket
qt.entityid as qc_ticket_entity_id,
qt.data.created_at as qc_ticket_created_at,
lookup_date(qt.data.created_at) as qc_ticket_created_date_key,
lookup_time(qt.data.created_at) as qc_ticket_created_time_key,
ticket_status.created_by as qc_ticket_created_by,
qt.data.goods_receipt_note_id as goods_receipt_note_id,
qt.data.id as qc_ticket_id,
qt.data.lost_quantity as qc_ticket_lost_quantity,
qt.data.product_id as qc_ticket_product_id,
qt.data.qc_reason_id as qc_reason_id,
qt.data.quantity as qc_ticket_quantity,
qt.data.status as qc_ticket_status,
qt.data.updated_at as qc_ticket_updated_at,
lookup_date(qt.data.updated_at) as qc_ticket_updated_date_key,
lookup_time(qt.data.updated_at) as qc_ticket_updated_time_key,
qt.data.updated_by as qc_ticket_updated_by,
qt.data.warehouse_id as qc_ticket_warehouse_id,
qt.data.wid as qc_ticket_wid,
lookupkey('product_detail_product_id',concat(qt.data.product_id,'wsr')) as qc_ticket_product_key,
lookupkey('warehouse_id',qt.data.warehouse_id) as qc_ticket_warehouse_id_key,
-- ticket_status
'' as ticket_status_created,
ticket_status.created_time as ticket_created_time,
lookup_date(ticket_status.created_time) as ticket_created_date_key,
lookup_time(ticket_status.created_time) as ticket_created_time_key,
'' as ticket_status_pending_reco,
ticket_status.pending_reco_time as ticket_pending_reco_time,
lookup_date(ticket_status.pending_reco_time) as ticket_pending_reco_date_key,
lookup_time(ticket_status.pending_reco_time) as ticket_pending_reco_time_key,
'' as ticket_status_bd_escalated,
ticket_status.bd_escalated_time as ticket_bd_escalated_time,
lookup_date(ticket_status.bd_escalated_time) as ticket_bd_escalated_date_key,
lookup_time(ticket_status.bd_escalated_time) as ticket_bd_escalated_time_key,
'' as ticket_status_marked_4_liquidn,
ticket_status.marked_for_liquidation_time as ticket_marked_4_liquidn_time,
lookup_date(ticket_status.marked_for_liquidation_time) as ticket_marked_4_liquidn_date_key,
lookup_time(ticket_status.marked_for_liquidation_time) as ticket_marked_4_liquidn_time_key,
'' as ticket_status_marked_4_supplier_return,
ticket_status.marked_for_supplier_return_time as ticket_marked_4_supplier_ret_time,
lookup_date(ticket_status.marked_for_supplier_return_time) as ticket_marked_4_sup_ret_date_key,
lookup_time(ticket_status.marked_for_supplier_return_time) as ticket_marked_4_sup_ret_time_key,
'' as ticket_status_invalid,
ticket_status.invalid_time as ticket_invalid_time,
lookup_date(ticket_status.invalid_time) as ticket_invalid_date_key,
lookup_time(ticket_status.invalid_time) as ticket_invalid_time_key,
'' as ticket_final_status_lost,
ticket_status.lost_time as ticket_lost_time,
lookup_date(ticket_status.lost_time) as ticket_lost_date_key,
lookup_time(ticket_status.lost_time) as ticket_lost_time_key,
'' as ticket_final_status_rejected,
ticket_status.rejected_time as ticket_reject_time,
lookup_date(ticket_status.rejected_time) as ticket_reject_date_key,
lookup_time(ticket_status.rejected_time) as ticket_reject_time_key,
'' as ticket_status_sent_2_liquidn,
ticket_status.sent_to_liquidation_time as ticket_sent_2_liquidn_time,
lookup_date(ticket_status.sent_to_liquidation_time) as ticket_sent_2_liquidn_date_key,
lookup_time(ticket_status.sent_to_liquidation_time) as ticket_sent_2_liquidn_time_key,
'' as ticket_status_sent_2_supp_ret,
ticket_status.sent_to_supplier_return_time as ticket_sent_2_supp_ret_time,
lookup_date(ticket_status.sent_to_supplier_return_time) as ticket_sent_2_supp_ret_date_key,
lookup_time(ticket_status.sent_to_supplier_return_time) as ticket_sent_2_supp_ret_time_key,
'' as ticket_status_wh_accepted,
ticket_status.warehouse_accepted_time as ticket_wh_accepted_time,
lookup_date(ticket_status.warehouse_accepted_time) as ticket_wh_accepted_date_key,
lookup_time(ticket_status.warehouse_accepted_time) as ticket_wh_accepted_time_key,
ticket_status.bd_accepted_time as ticket_bd_accepted_time,
lookup_date(ticket_status.bd_accepted_time) as ticket_bd_accepted_date_key,
lookup_time(ticket_status.bd_accepted_time) as ticket_bd_accepted_time_key,
ticket_status.bd_accepted_by,
ticket_status.warehouse_accepted_by,
ticket_status.sent_to_supplier_return_by,
ticket_status.lost_by,
ticket_status.rejected_by,
ticket_status.invalid_by,
ticket_status.sent_to_liquidation_by,
ticket_status.marked_for_supplier_return_by,
ticket_status.marked_for_liquidation_by,
ticket_status.bd_escalated_by,
ticket_status.pending_reco_by
from bigfoot_snapshot.dart_wsr_scp_warehouse_qc_ticket_1_view as qt
left join 
(select data.ticket_id as ticket_id,
max(case when data.status = 'created' then data.status_time end) as created_time,
max(case when data.status = 'bd_accepted' then data.status_time end) as bd_accepted_time,
max(case when data.status = 'warehouse_accepted' then data.status_time end) as warehouse_accepted_time,
max(case when data.status = 'sent_to_supplier_return' then data.status_time end) as sent_to_supplier_return_time,
max(case when data.status = 'lost' then data.status_time end) as lost_time,
max(case when data.status = 'rejected' then data.status_time end) as rejected_time,
max(case when data.status = 'invalid' then data.status_time end) as invalid_time,
max(case when data.status = 'sent_to_liquidation' then data.status_time end) as sent_to_liquidation_time,
max(case when data.status = 'marked_for_supplier_return' then data.status_time end) as marked_for_supplier_return_time,
max(case when data.status = 'marked_for_liquidation' then data.status_time end) as marked_for_liquidation_time,
max(case when data.status = 'bd_escalated' then data.status_time end) as bd_escalated_time,
max(case when data.status = 'pending_reco' then data.status_time end) as pending_reco_time,
max(case when data.status = 'created' then data.created_by end) as created_by,
max(case when data.status = 'bd_accepted' then data.created_by end) as bd_accepted_by,
max(case when data.status = 'warehouse_accepted' then data.created_by end) as warehouse_accepted_by,
max(case when data.status = 'sent_to_supplier_return' then data.created_by end) as sent_to_supplier_return_by,
max(case when data.status = 'lost' then data.created_by end) as lost_by,
max(case when data.status = 'rejected' then data.created_by end) as rejected_by,
max(case when data.status = 'invalid' then data.created_by end) as invalid_by,
max(case when data.status = 'sent_to_liquidation' then data.created_by end) as sent_to_liquidation_by,
max(case when data.status = 'marked_for_supplier_return' then data.created_by end) as marked_for_supplier_return_by,
max(case when data.status = 'marked_for_liquidation' then data.created_by end) as marked_for_liquidation_by,
max(case when data.status = 'bd_escalated' then data.created_by end) as bd_escalated_by,
max(case when data.status = 'pending_reco' then data.created_by end) as pending_reco_by
from bigfoot_snapshot.dart_wsr_scp_warehouse_ticket_status_1_view 
group  by data.ticket_id) as ticket_status on qt.entityid = ticket_status.ticket_id

UNION ALL

select 'fki' as warehouse_company,
-- qc_ticket
qt2.entityid as qc_ticket_entity_id,
qt2.data.created_at as qc_ticket_created_at,
lookup_date(qt2.data.created_at) as qc_ticket_created_date_key,
lookup_time(qt2.data.created_at) as qc_ticket_created_time_key,
ticket_status.created_by as qc_ticket_created_by,
qt2.data.goods_receipt_note_id as goods_receipt_note_id,
qt2.data.id as qc_ticket_id,
qt2.data.lost_quantity as qc_ticket_lost_quantity,
qt2.data.product_id as qc_ticket_product_id,
qt2.data.qc_reason_id as qc_reason_id,
qt2.data.quantity as qc_ticket_quantity,
qt2.data.status as qc_ticket_status,
qt2.data.updated_at as qc_ticket_updated_at,
lookup_date(qt2.data.updated_at) as qc_ticket_updated_date_key,
lookup_time(qt2.data.updated_at) as qc_ticket_updated_time_key,
qt2.data.updated_by as qc_ticket_updated_by,
qt2.data.warehouse_id as qc_ticket_warehouse_id,
qt2.data.wid as qc_ticket_wid,
lookupkey('product_detail_product_id',concat(qt2.data.product_id,'fki')) as qc_ticket_product_key,
lookupkey('warehouse_id',qt2.data.warehouse_id) as qc_ticket_warehouse_id_key,
-- ticket_status
'' as ticket_status_created,
ticket_status.created_time as ticket_created_time,
lookup_date(ticket_status.created_time) as ticket_created_date_key,
lookup_time(ticket_status.created_time) as ticket_created_time_key,
'' as ticket_status_pending_reco,
ticket_status.pending_reco_time as ticket_pending_reco_time,
lookup_date(ticket_status.pending_reco_time) as ticket_pending_reco_date_key,
lookup_time(ticket_status.pending_reco_time) as ticket_pending_reco_time_key,
'' as ticket_status_bd_escalated,
ticket_status.bd_escalated_time as ticket_bd_escalated_time,
lookup_date(ticket_status.bd_escalated_time) as ticket_bd_escalated_date_key,
lookup_time(ticket_status.bd_escalated_time) as ticket_bd_escalated_time_key,
'' as ticket_status_marked_4_liquidn,
ticket_status.marked_for_liquidation_time as ticket_marked_4_liquidn_time,
lookup_date(ticket_status.marked_for_liquidation_time) as ticket_marked_4_liquidn_date_key,
lookup_time(ticket_status.marked_for_liquidation_time) as ticket_marked_4_liquidn_time_key,
'' as ticket_status_marked_4_supplier_return,
ticket_status.marked_for_supplier_return_time as ticket_marked_4_supplier_ret_time,
lookup_date(ticket_status.marked_for_supplier_return_time) as ticket_marked_4_sup_ret_date_key,
lookup_time(ticket_status.marked_for_supplier_return_time) as ticket_marked_4_sup_ret_time_key,
'' as ticket_status_invalid,
ticket_status.invalid_time as ticket_invalid_time,
lookup_date(ticket_status.invalid_time) as ticket_invalid_date_key,
lookup_time(ticket_status.invalid_time) as ticket_invalid_time_key,
'' as ticket_final_status_lost,
ticket_status.lost_time as ticket_lost_time,
lookup_date(ticket_status.lost_time) as ticket_lost_date_key,
lookup_time(ticket_status.lost_time) as ticket_lost_time_key,
'' as ticket_final_status_rejected,
ticket_status.rejected_time as ticket_reject_time,
lookup_date(ticket_status.rejected_time) as ticket_reject_date_key,
lookup_time(ticket_status.rejected_time) as ticket_reject_time_key,
'' as ticket_status_sent_2_liquidn,
ticket_status.sent_to_liquidation_time as ticket_sent_2_liquidn_time,
lookup_date(ticket_status.sent_to_liquidation_time) as ticket_sent_2_liquidn_date_key,
lookup_time(ticket_status.sent_to_liquidation_time) as ticket_sent_2_liquidn_time_key,
'' as ticket_status_sent_2_supp_ret,
ticket_status.sent_to_supplier_return_time as ticket_sent_2_supp_ret_time,
lookup_date(ticket_status.sent_to_supplier_return_time) as ticket_sent_2_supp_ret_date_key,
lookup_time(ticket_status.sent_to_supplier_return_time) as ticket_sent_2_supp_ret_time_key,
'' as ticket_status_wh_accepted,
ticket_status.warehouse_accepted_time as ticket_wh_accepted_time,
lookup_date(ticket_status.warehouse_accepted_time) as ticket_wh_accepted_date_key,
lookup_time(ticket_status.warehouse_accepted_time) as ticket_wh_accepted_time_key,
ticket_status.bd_accepted_time as ticket_bd_accepted_time,
lookup_date(ticket_status.bd_accepted_time) as ticket_bd_accepted_date_key,
lookup_time(ticket_status.bd_accepted_time) as ticket_bd_accepted_time_key,
ticket_status.bd_accepted_by,
ticket_status.warehouse_accepted_by,
ticket_status.sent_to_supplier_return_by,
ticket_status.lost_by,
ticket_status.rejected_by,
ticket_status.invalid_by,
ticket_status.sent_to_liquidation_by,
ticket_status.marked_for_supplier_return_by,
ticket_status.marked_for_liquidation_by,
ticket_status.bd_escalated_by,
ticket_status.pending_reco_by
from bigfoot_snapshot.dart_fki_scp_warehouse_qc_ticket_1_view as qt2
left join 
(select data.ticket_id as ticket_id,
max(case when data.status = 'created' then data.status_time end) as created_time,
max(case when data.status = 'bd_accepted' then data.status_time end) as bd_accepted_time,
max(case when data.status = 'warehouse_accepted' then data.status_time end) as warehouse_accepted_time,
max(case when data.status = 'sent_to_supplier_return' then data.status_time end) as sent_to_supplier_return_time,
max(case when data.status = 'lost' then data.status_time end) as lost_time,
max(case when data.status = 'rejected' then data.status_time end) as rejected_time,
max(case when data.status = 'invalid' then data.status_time end) as invalid_time,
max(case when data.status = 'sent_to_liquidation' then data.status_time end) as sent_to_liquidation_time,
max(case when data.status = 'marked_for_supplier_return' then data.status_time end) as marked_for_supplier_return_time,
max(case when data.status = 'marked_for_liquidation' then data.status_time end) as marked_for_liquidation_time,
max(case when data.status = 'bd_escalated' then data.status_time end) as bd_escalated_time,
max(case when data.status = 'pending_reco' then data.status_time end) as pending_reco_time,
max(case when data.status = 'created' then data.created_by end) as created_by,
max(case when data.status = 'bd_accepted' then data.created_by end) as bd_accepted_by,
max(case when data.status = 'warehouse_accepted' then data.created_by end) as warehouse_accepted_by,
max(case when data.status = 'sent_to_supplier_return' then data.created_by end) as sent_to_supplier_return_by,
max(case when data.status = 'lost' then data.created_by end) as lost_by,
max(case when data.status = 'rejected' then data.created_by end) as rejected_by,
max(case when data.status = 'invalid' then data.created_by end) as invalid_by,
max(case when data.status = 'sent_to_liquidation' then data.created_by end) as sent_to_liquidation_by,
max(case when data.status = 'marked_for_supplier_return' then data.created_by end) as marked_for_supplier_return_by,
max(case when data.status = 'marked_for_liquidation' then data.created_by end) as marked_for_liquidation_by,
max(case when data.status = 'bd_escalated' then data.created_by end) as bd_escalated_by,
max(case when data.status = 'pending_reco' then data.created_by end) as pending_reco_by
from bigfoot_snapshot.dart_fki_scp_warehouse_ticket_status_1_view 
group  by data.ticket_id) ticket_status on qt2.entityid = ticket_status.ticket_id
) t1;
